### ISSUE TITLE
Why the number of sequences in ccs.fasta is less than the number in flnc.fasta?

### ISSUE THREAD

**Issue by Moo-cow** [shizhuoxing/Full-Length-RNA-Analysis-Best-Practice#5]
Hi ,
I took the iso-seq at BGI.
I used the official PacBio pipeline flnc.fasta file which has only a hundred sequences, which is obviously not correct.
I used your pipeline and found that the number of sequences in ccs.fasta is less than the number in flnc.fasta.
Please tell me is this normal?
Thanks.

<img width="709" alt="7C0E85ED-115F-421A-A7CD-753986BE9C0A" src="https://user-images.githubusercontent.com/26018594/234784273-52c0be8c-995f-41c8-963d-7600c032a54d.png">

**Comment by shizhuoxing** [comment]
Hi,
That's because we're using BGI patented IsoLink-seq protocol: https://github.com/shizhuoxing/BGI-Full-Length-RNA-Analysis-Pipeline/wiki.

**Comment by Moo-cow** [comment]
Wow~
Thank you !
